-- NOTE: Al agregar tablas o campos nuevos recuerda que se deben usar minusculas y _
-- Para más detalles referirse a la documentación oficicial de PostgreSQL

create schema if not exists infaut;

-- Tabla de cursos
create table infaut.curso (
    id_curso integer generated by default as identity not null,
    descripcion text not null,
    constraint curso_pkey primary key (id_curso)
) tablespace pg_default;

-- Tabla de aulas
create table infaut.aula (
    id_aula integer generated by default as identity not null,
    descripcion text not null,
    constraint aula_pkey primary key (id_aula)
) tablespace pg_default;

-- Tabla de docentes
create table infaut.docente (
    id_docente integer generated by default as identity not null,
    nombre text not null,
    apellido text not null,
    ci integer not null,
    constraint docente_pkey primary key (id_docente)
) tablespace pg_default;

-- Tabla de alumnos
create table infaut.alumno (
    id_alumno integer generated by default as identity not null,
    nombre text not null,
    apellido text not null,
    ci integer not null,
    id_curso integer not null,
    constraint alumno_pkey primary key (id_alumno),
    constraint alumno_id_curso_fkey foreign key (id_curso) references infaut.curso (id_curso)
) tablespace pg_default;

-- Tabla para registrar asistencias
CREATE TABLE asistencia (
    id_asistencia SERIAL PRIMARY KEY,
    id_alumno INT NOT NULL,
    id_aula INT,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_alumno) REFERENCES alumno(id_alumno),
    FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

-- Tabla de huellas
-- id_huella auto-generado
create table infaut.huella (
    id_huella integer generated by default as identity not null,
    imagen_huella bytea not null,
    id_alumno integer not null,
    constraint huella_pkey primary key (id_huella),
    constraint huella_id_alumno_fkey foreign key (id_alumno) references infaut.alumno (id_alumno)
) tablespace pg_default;

-- Tabla de materias
create table infaut.materia (
    id_materia integer generated by default as identity not null,
    nombre text not null,
    hora_inicio text not null, -- usar time si deseas operaciones sobre horas
    hora_fin text not null,    -- usar time si deseas operaciones sobre horas
    aula_id_aula integer not null,
    constraint materia_pkey primary key (id_materia),
    constraint materia_aula_id_aula_fkey foreign key (aula_id_aula) references infaut.aula (id_aula)
) tablespace pg_default;

-- Tablas "detalle". Aun es comun llamarlas detalle_entidad.
-- A fin de dejar mas claro el rol de estas tablas, se las nombra de la sgte manera:
-- * ent1_ent2 (dos entidades relacionadas de varios a varios)
--      o
-- * ent1_ent2_ent3 (tres entidades relacionadas de varios a varios)

-- Relacion muchos a muchos: curso <-> materia
create table infaut.curso_materia (
    id_materia integer not null,
    id_curso integer not null,
    constraint detalle_curso_id_curso_fkey foreign key (id_curso) references infaut.curso (id_curso) on update cascade on delete cascade,
    constraint detalle_curso_id_materia_fkey foreign key (id_materia) references infaut.materia (id_materia) on update cascade on delete cascade
) tablespace pg_default;

-- Relacion muchos a muchos: docente <-> materia
create table infaut.docente_materia (
    id_docente integer not null,
    id_materia integer not null,
    constraint detalle_docente_id_docente_fkey foreign key (id_docente) references infaut.docente (id_docente),
    constraint detalle_docente_id_materia_fkey foreign key (id_materia) references infaut.materia (id_materia)
) tablespace pg_default;

-- Relacion huella <-> alumno <-> materia
-- Referencia solo id_huella como FK para mantener id_huella auto-generado
-- id_alumno y id_materia se almacenan para consultas y claridad
create table infaut.huella_alumno_materia (
    id_huella integer not null,
    id_alumno integer not null,
    id_materia integer not null,
    hora_entrada text not null, -- usar time si deseas operaciones sobre horas
    constraint detalle_huella_pkey primary key (id_huella, id_alumno, id_materia),
    constraint detalle_huella_id_huella_fkey foreign key (id_huella) references infaut.huella (id_huella) on update cascade on delete cascade
) tablespace pg_default;
